export const NO_USER = { email: "", id: -1, role: -1 };

export const COUNTRIES = [
    { name: "Austria", code: "AT" },
    { name: "Albania", code: "AL" },
    { name: "Andorra", code: "AD" },
    { name: "Belgium", code: "BE" },
    { name: "Bulgaria", code: "BG" },
    { name: "Bosnia and Herzegovina", code: "BA" },
    { name: "Belarus", code: "BY" },
    { name: "Switzerland", code: "CH" },
    { name: "Czechia", code: "CZ" },
    { name: "Germany", code: "DE" },
    { name: "Denmark", code: "DK" },
    { name: "Estonia", code: "EE" },
    { name: "Spain", code: "ES" },
    { name: "Finland", code: "FI" },
    { name: "Faroe Islands", code: "FO" },
    { name: "France", code: "FR" },
    { name: "United Kingdom", code: "GB" },
    { name: "Gibraltar", code: "GI" },
    { name: "Greece", code: "GR" },
    { name: "Croatia", code: "HR" },
    { name: "Hungary", code: "HU" },
    { name: "Ireland", code: "IE" },
    { name: "Iceland", code: "IS" },
    { name: "Italy", code: "IT" },
    { name: "Jersey", code: "JE" },
    { name: "Liechtenstein", code: "LI" },
    { name: "Lithuania", code: "LT" },
    { name: "Luxembourg", code: "LU" },
    { name: "Latvia", code: "LV" },
    { name: "Monaco", code: "MC" },
    { name: "Moldova", code: "MD" },
    { name: "Montenegro", code: "ME" },
    { name: "North Macedonia", code: "MK" },
    { name: "Malta", code: "MT" },
    { name: "Netherlands", code: "NL" },
    { name: "Norway", code: "NO" },
    { name: "Poland", code: "PL" },
    { name: "Portugal", code: "PT" },
    { name: "Romania", code: "RO" },
    { name: "Serbia", code: "RS" },
    { name: "Russia", code: "RU" },
    { name: "Sweden", code: "SE" },
    { name: "Slovenia", code: "SI" },
    { name: "Svalbard and Jan Mayen", code: "SJ" },
    { name: "Slovakia", code: "SK" },
    { name: "San Marino", code: "SM" },
    { name: "Turkey", code: "TR" },
    { name: "Ukraine", code: "UA" },
    { name: "Vatican City", code: "VA" },
];
